### ISSUE TITLE
Lucky pot amount

### ISSUE THREAD

**Issue by alexpopa-work** [coder-amogh/pyHoneygain#4]
Hey, first of all thanks for the repo, it's great for building a minimal custom dashboard.
I started using it some time ago and it works great, the one thing that is peculiar is the lucky pot. 
It seems that the returned amount is always 10. Tested it for more than a week, it's always 10.
Is this a limitation of the api calls or am I unlucky? From the interface the amount was different every day.
Thanks!

**Comment by coder-amogh** [comment]
Hello, good to know you're liking my work!
Could you share the code please? And is it like a script run by a crontab?

**Comment by alexpopa-work** [comment]
Hey @coder-amogh, thanks for getting back to me.
The code is simple, here's the snippet responsible for the lucky pot:

```
from pyHoneygain import HoneyGain

JWT_TOKEN = "..."
user = HoneyGain()
user.set_jwt_token(JWT_TOKEN)
hp = user.open_honeypot()
```

Yes, it's a script run everyday by a crontab.
Thanks!

**Comment by coder-amogh** [comment]
Try adding some random delay, because opening through dashboard there's always some kind of delay and the crontab will always run at the same time. Honeypot is, as far as I've seen, is mostly determined on the time you open it. So try adding something like this:

```PYTHON
import time, random
time.sleep(random.randint(10, 60))
```

But mostly a lot of people get 10 everyday, so there might not be any issue on your end!

Keep me posted :)

**Comment by alexpopa-work** [comment]
Thanks for the suggestion! I'll try adding random sleep and keep the results monitored. 
Thanks again!

**Comment by alexpopa-work** [comment]
@coder-amogh today I got 20! So I guess I was just unlucky the previous days.
Thanks for your assistance.
